apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellochart
  labels:
    app: hello-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - name: hello-app
        image: {{ .Values.image.name }}
        resources:
          limits:
            memory: "{{ .Values.resources.limits.memory }}"
            cpu: "{{ .Values.resources.limits.cpu }}"
        ports:
        - containerPort: {{ .Values.container.port }}

            
            